# Generated by Django 5.1.5 on 2025-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('photo_profile', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
